spring:
  kafka:
    bootstrap-servers: kafka1:9092,kafka2:9092,kafka3:9092
#    producer:
#      key-serializer: org.apache.kafka.common.serialization.StringSerializer
#      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
#      acks: all
#      retries: 3
#      batch-size: 16384
#      linger-ms: 10
#      buffer-memory: 33554432
  application:
    name: Task Microservice
  datasource:
    url: jdbc:postgresql://task-postgres:5432/task
    username: dev
    password: dev
    driver-class-name: org.postgresql.Driver
    data:
      jdbc:
        dialect: postgresql